insert into food_item (id, name)
values (UUID(), 'Wassereis'),
       (UUID(), 'Sandwich'),
       (UUID(), 'Pizza'),
       (UUID(), 'Instantnudeln'),
       (UUID(), 'Erfrischungsstäbchen'),
       (UUID(), 'Crunchips'),
       (UUID(), 'Pizzaschnecken'),
       (UUID(), 'Götterspeise'),
       (UUID(), 'Geramont'),
       (UUID(), 'Salami-Snack'),
       (UUID(), 'Mikadostäbchen'),
       (UUID(), 'Schoko-Butterkekse'),
       (UUID(), 'Kuchen'),
       (UUID(), 'Cornetto'),
       (UUID(), 'Tortilla-Chips'),
       (UUID(), 'Schokobons'),
       (UUID(), 'Tomatensalat'),
       (UUID(), 'Gurkensalat'),
       (UUID(), 'Hähnchencurry mit Reis'),
       (UUID(), 'Hähnchen süß-sauer'),
       (UUID(), 'Toffifee'),
       (UUID(), 'Frühlingsrollen'),
       (UUID(), 'Marshmallows'),
       (UUID(), 'Wrap'),
       (UUID(), 'Schokolade'),
       (UUID(), 'Pringles'),
       (UUID(), 'Nussmix'),
       (UUID(), 'Kinderland'),
       (UUID(), 'Trockenobst'),
       (UUID(), 'Haribo'),
       (UUID(), 'TicTac'),
       (UUID(), 'Mini-Frühlingsrollen'),
       (UUID(), 'Milchschnitte'),
       (UUID(), 'Bratwurst'),
       (UUID(), 'Paprika'),
       (UUID(), 'Gurke'),
       (UUID(), 'Brötchen'),
       (UUID(), 'Waffeln'),
       (UUID(), 'Mozzarella'),
       (UUID(), 'Blattsalat'),
       (UUID(), 'Grillhähnchen'),
       (UUID(), 'Hähnchensteak'),
       (UUID(), 'Bolognese');